{
 "title": "Grafana project",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{node=\"$node\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", node=\"$node\", namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of pods on node",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=\"$node\"}) by (node)"
    }
   ]
  },
  {
   "title": "CPU usage by core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(1 - rate(node_cpu_seconds_total{instance=\"$node\"}[5m])) by (node)"
    }
   ]
  },
  {
   "title": "CPU by percentage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"$node\"}[1m])) * 100)"
    }
   ]
  },
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Number of pods restarts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Number of pods on namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Number of deployments on namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_annotations{namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "CPU usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{namespace=\"$namespace\"}[1m])) by (namespace)"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_network_transmit_bytes_total{namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Memory usage on Namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 38 },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic on pod",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(container_network_transmit_bytes_total{pod=\"$pod\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Disk I/O read and write",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{pod=\"$pod\"}) by (pod)"
      }
     ]
    },
    {
     "title": "CPU by percentage %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\", pod=\"$pod\"}[5m])) * 100)"
      }
     ]
    },
    {
     "title": "Pod age",
     "type": "stat",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - kube_pod_created{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Average memory usage",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{pod=\"$pod\"}) by (pod)"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 9, "y": 18 },
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{pod=\"$pod\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container memory usage",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{container=\"$container\"}) by (container)"
      }
     ]
    },
    {
     "title": "CPU usage per container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 72 },
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{container=\"$container\"}[1m]))"
      }
     ]
    }
   ]
  }
 ]
}