{
 "title": "Grafana project",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{node=\"$node\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", node=\"$node\", namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of pods on node",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=\"$node\"}) by (node)"
    }
   ]
  },
  {
   "title": "CPU by percentage %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"$node\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU usage by core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "milicores" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"$node\"}[1m])) by (node) * 1000",
     "legendFormat": "$node"
    }
   ]
  },
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Number of pods restarts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Number of pods on namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Number of deployments on namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_created{namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "CPU usage by namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "milicores" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{namespace=\"$namespace\"}[1m])) by (namespace) * 1000"
    }
   ]
  },
  {
   "title": "Network I/O receive/transmit by namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (namespace)",
     "legendFormat": "received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (namespace)",
     "legendFormat": "transmitted"
    }
   ]
  },
  {
   "title": "Memory usage on Namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "$namespace"
    }
   ]
  },
  { "title": "Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Network I/O receive/transmit by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{node=\"$node\", namespace=\"$namespace\", pod=\"$pod\"}[5m])) by (pod)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{node=\"$node\", namespace=\"$namespace\", pod=\"$pod\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Disk I/O read/write for pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{node=\"$node\", namespace=\"$namespace\", pod=\"$pod\"}[5m])) by (pod)",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{node=\"$node\", namespace=\"$namespace\", pod=\"$pod\"}[5m])) by (pod)",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "CPU by percentage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\"}[1m])) / sum(machine_cpu_cores{node=\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Pod age",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_pod_created{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Average memory usage per pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(container_memory_usage_bytes{pod=\"$pod\"}[5m])) by (pod)",
     "legendFormat": "Memory: $pod "
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "milicores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\"}[1m])) * 1000",
     "legendFormat": "CPU usage: $pod"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{node=\"$node\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container)",
     "legendFormat": "$container CPU"
    }
   ]
  },
  {
   "title": "CPU usage per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "milicores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=\"$node\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[5m])) by (container) * 1000",
     "legendFormat": "$container CPU %"
    }
   ]
  }
 ]
}